#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.0f6_27ab2135bccf"
#define UNITY_VERSION_FULL_NICE "2019.3.0f6 (27ab2135bccf)"
#define UNITY_VERSION_BLD 2599713
#define UNITY_VERSION_DATE 1579669995
#define UNITY_VERSION_WIN "2019.3.0.2599713"
#define UNITY_VERSION_BRANCH "2019.3/staging"
